name: FunPot Core CD

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

permissions:
  contents: read

env:
  BINARY_NAME: funpot-core

jobs:
  publish-and-deploy:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    container:
      image: docker.gitea.com/runner-images:ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: development
            branch: dev
            webhook_secret: DEV_DEPLOY_WEBHOOK_URL
          - environment: production
            branch: main
            webhook_secret: PROD_DEPLOY_WEBHOOK_URL
    if: startsWith(github.ref, 'refs/heads/') && github.ref_name == matrix.branch
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...

      - name: Build Linux binary
        run: |
          set -eu
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o "dist/${BINARY_NAME}" ./cmd/server
