name: FunPot Core CI

on:
  push:
    branches: ["main", "dev", "feature/**"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.gitea.com/runner-images:ubuntu-latest
      # options удаляем — раннер сам монтирует docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: Validate formatting
        run: |
          fmt_out=$(gofmt -l .)
          if [ -n "$fmt_out" ]; then
            echo "The following files need gofmt:" >&2
            echo "$fmt_out" >&2
            exit 1
          fi

      - name: Verify modules
        run: go mod tidy

      - name: Check module diff
        run: |
          if [ -n "$(git status --short go.mod go.sum)" ]; then
            echo "go.mod or go.sum changed after go mod tidy. Run go mod tidy locally." >&2
            git diff -- go.mod go.sum >&2
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t funpot-core:ci .

      - name: Smoke test container
        run: |
          set -e
          cid=$(docker run -d -e FUNPOT_ENV=ci --name funpot-ci-test funpot-core:ci)
          trap 'docker logs "$cid" || true; docker rm -f "$cid" >/dev/null 2>&1 || true' EXIT
          # ждём, пока приложение поднимется
          for i in {1..15}; do
            if docker exec "$cid" sh -c 'wget -qO- http://127.0.0.1:8080/healthz >/dev/null 2>&1'; then
              break
            fi
            sleep 2
          done
          docker exec "$cid" sh -c 'wget -qO- http://127.0.0.1:8080/readyz >/dev/null'
